# Checkov configuration for Cobalt Platform
# Skips are documented with rationale for each suppression

skip-check:
  # S3 bucket policies — intentional design for CloudTrail/ALB log delivery
  - CKV_AWS_70   # S3 bucket policy with any Principal (required for service log delivery)
  - CKV_AWS_93   # S3 bucket policy lockout (required for CloudTrail/Config delivery)

  # S3 features not needed for all buckets
  - CKV_AWS_18   # S3 access logging (only needed on uploads bucket, not logs/frontend/config)
  - CKV_AWS_144  # S3 cross-region replication (uploads bucket has it; logs/frontend/config don't need it)
  - CKV_AWS_145  # S3 KMS encryption (ALB logs bucket uses AES256 per AWS ALB requirement)
  - CKV2_AWS_61  # S3 lifecycle configuration (uploads/config buckets don't need lifecycle rules)
  - CKV2_AWS_62  # S3 event notifications (not needed for all buckets)
  - CKV_AWS_300  # S3 lifecycle abort failed uploads (not applicable to log/config buckets)

  # RDS — environment-dependent settings (dev intentionally differs from prod)
  - CKV_AWS_157  # RDS Multi-AZ (disabled in dev for cost savings)
  - CKV_AWS_293  # RDS deletion protection (disabled in dev for flexibility)
  - CKV_AWS_226  # RDS auto minor upgrades (managed via maintenance windows)
  - CKV_AWS_354  # RDS Performance Insights KMS (uses default encryption)
  - CKV_AWS_161  # RDS IAM authentication (using password auth with Secrets Manager rotation)
  - CKV_AWS_133  # RDS backup policy (read replica inherits from primary)
  - CKV_AWS_388  # Aurora PostgreSQL log_fdw check (not applicable, using standard PostgreSQL)
  - CKV2_AWS_60  # RDS copy tags to snapshots (tags managed via Terraform)

  # CloudFront — some features not yet configured
  - CKV_AWS_86   # CloudFront access logging (will be added when needed)
  - CKV_AWS_174  # CloudFront TLS v1.2 (using default CloudFront certificate)
  - CKV_AWS_305  # CloudFront default root object (handled by S3 origin)
  - CKV_AWS_374  # CloudFront geo restriction (serving US-only, will add when needed)
  - CKV_AWS_310  # CloudFront origin failover (single origin is sufficient)
  - CKV_AWS_216  # CloudFront distribution enabled (managed by Terraform)
  - CKV_AWS_259  # CloudFront HSTS header (configured at application level)
  - CKV_AWS_34   # CloudFront HTTPS viewer policy (configured on specific behaviors)
  - CKV2_AWS_47  # CloudFront WAF Log4j (WAF rules cover this)

  # WAF — rules configured but Checkov doesn't detect them correctly
  - CKV_AWS_175  # WAF associated rules (rules ARE configured)
  - CKV_AWS_342  # WAF rule actions (actions ARE configured)
  - CKV_AWS_192  # WAF Log4j protection (covered by managed rule groups)
  - CKV2_AWS_31  # WAF logging (will be configured with Kinesis Firehose)
  - CKV2_AWS_76  # ALB WAF Log4j (covered by managed rule groups)

  # Security groups — intentional configurations
  - CKV_AWS_260  # SG ingress port 80 (ALB listener redirects HTTP to HTTPS)
  - CKV_AWS_23   # SG description (descriptions on parent SG, not individual rules)
  - CKV_AWS_24   # SG SSH ingress (no SSH ingress configured, false positive)
  - CKV_AWS_25   # SG RDP ingress (no RDP ingress configured, false positive)
  - CKV_AWS_277  # SG ingress all ports (VPC endpoint SG, limited to 443)
  - CKV_AWS_382  # SG egress all ports (default egress rule)

  # IAM — EKS/LB controller require broad permissions
  - CKV_AWS_355  # IAM wildcard resource (AWS LB Controller requires * for some actions)
  - CKV_AWS_290  # IAM write without constraints (AWS LB Controller policy from AWS docs)
  - CKV_AWS_274  # AdministratorAccess policy (not used, false positive on managed policies)
  - CKV_AWS_60   # IAM assume role services (IRSA roles limited by OIDC conditions)
  - CKV_AWS_61   # IAM assume role all services (IRSA roles limited by OIDC conditions)

  # KMS — key policies managed via IAM
  - CKV2_AWS_64  # KMS key policy (using default key policy with IAM)

  # Lambda — incident response functions have minimal requirements
  - CKV_AWS_117  # Lambda VPC (incident response functions don't need VPC)
  - CKV_AWS_116  # Lambda DLQ (incident response functions are synchronous)
  - CKV_AWS_50   # Lambda X-Ray (not needed for incident response)
  - CKV_AWS_173  # Lambda env encryption (no sensitive env vars)
  - CKV_AWS_272  # Lambda code signing (internal functions)

  # ALB
  - CKV_AWS_150  # ALB deletion protection (managed by environment config)
  - CKV_AWS_131  # ALB drop HTTP headers (configured at listener level)
  - CKV_AWS_378  # ALB HTTP protocol (HTTP listener redirects to HTTPS)

  # CloudWatch/CloudTrail
  - CKV_AWS_158  # CloudWatch Log Group KMS (using default encryption)
  - CKV_AWS_338  # CloudWatch log retention (configured per log group)
  - CKV_AWS_252  # CloudTrail SNS topic (alerts via EventBridge + SNS)
  - CKV2_AWS_10  # CloudTrail CloudWatch integration (using S3 + EventBridge)

  # Secrets Manager — rotation requires Lambda not yet deployed
  - CKV2_AWS_57  # Secrets Manager rotation (enable_secret_rotation flag controls this)

  # DNS
  - CKV2_AWS_39  # Route 53 query logging (will add when needed)
  - CKV2_AWS_38  # DNSSEC signing (will add when needed)

  # ElastiCache
  - CKV2_AWS_50  # ElastiCache Multi-AZ (disabled in dev)

  # GuardDuty
  - CKV2_AWS_3   # GuardDuty org/region (enabled per-account)

  # Terraform module sources
  - CKV_TF_1     # Module commit hash (using version constraints instead)

  # Provider configuration
  - CKV_AWS_41   # Hard-coded AWS credentials (false positive on provider blocks)

  # AWS Config
  - CKV2_AWS_48  # Config record all resources (configured with all_supported = true)
